### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by drepo** [richardasaurus/wiki-api#6]
I have installed from pip. There are a couple things that prohibit this from working in python 3 environment (mostly urllib), please try to fix them when you have time. 

Also on line wikiapi.py#75, if possible, change .find() to .children() to avoid side effects arising from deeply nested "p" tags not relevant to the summary being extracted.

PS: Would have loved a pull request, but the state of local copy of code is terribly mutated.

**Comment by richardasaurus** [comment]
I'm having a look into this right now :+1:

**Comment by richardasaurus** [comment]
version 1.2.0 is now on PyPi which adds support for all python versions

**Comment by drepo** [comment]
Been here after while. Thanks for that! :+1:
